# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload-video
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/4bcbffea-e960-4b62-b491-e812b3233a35/transcription
Content-Type: application/json

{
    "prompt": "NodeJS"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
    "prompt": "Gere um resumo sucinto da transcricao do video a seguir '''{transcription}''' ",
    "temperature": 0.5,
    "videoId": "4bcbffea-e960-4b62-b491-e812b3233a35"
}